### PR TITLE
Give the full InChI (closes #948)

### LINKED ISSUE #948: InChI not shown in full
It visualizes the InChI as given in Wikidata, and lacks the `InChI=` prefix.

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by Daniel-Mietchen** [comment]
Works fine. Does/ should something similar apply to InChIKey?

**Comment by egonw** [comment]
> Does/ should something similar apply to InChIKey?

I need to check. Normally it doesn't come with a prefix, but I have seen that recently. I would suggest not to use it.

**Comment by egonw** [comment]
I checked. Formally, the InChIKey is with a `InChIKey=` prefix. But I still don't want to add that. Common practice there is really without.

**Comment by fnielsen** [comment]
I do not understand the headers "IDpred" and "Finalid". Could we give the some names that I can understand?

**Pull request merged**
