### PR TITLE
better literature for chemicals and fixed 'fatty acid' literature

### PR DESCRIPTION
**Pull request by egonw**
The problem here was that it also showed biological pathways. This is fixed by inverting the 'part of'. When debugging, I extended the query to record the 'via', which I found sufficiently helpful, that I kept that too.

### CODE REVIEW

**Comment by egonw** [comment]
I actually ran into #461 and applied that query update there too, as well as the 'date' trick reported in that issue.

**Comment by Daniel-Mietchen** [comment]
Looks good to me.

**Comment by egonw** [comment]
`tox -e flake8` fails on the branch, but that's due to a fix in the master commit it was branched from. I manually/locally merged into master (on a test branch), and then `tox -e flake8` comes out green.

**Comment by fnielsen** [comment]
I am wondering whether we have an example of a chemical where (all) the combination of "via" is there, - just to see that it works.

**Pull request merged**
