### PR TITLE
improved colour scale for topic orgs map

### PR DESCRIPTION
**Pull request by Daniel-Mietchen**
Initial attempt to address #1084

### CODE REVIEW

**Comment by Daniel-Mietchen** [comment]
Looks better. Probably need to drop the "results" from "10 results". 

Screen Shot 2020-03-24 at 01 11 03
Screen Shot 2020-03-24 at 01 11 55

**Comment by Daniel-Mietchen** [comment]
Would be great to arrange the colours such that the least occupied layer (i.e. highest numbers) are always displayed on top. May require changing the direction of the IF clause.

**Comment by Daniel-Mietchen** [comment]
I played around with color rearrangement, but it does not seem to be possible to specify the order in which the layers are being stacked for display.

**Comment by Daniel-Mietchen** [comment]
In terms of changing direction of the IF clause, that query is [here](https://www.wikidata.org/w/index.php?title=User:Daniel_Mietchen/Sandbox4URLshortening&oldid=1144061778).

**Comment by Daniel-Mietchen** [comment]
Not sure what you mean by the fewer dots. If that refers to the two pics in https://github.com/fnielsen/scholia/pull/1085#issuecomment-603021008 , then they do not have to be compared against each other but against the two pics in https://github.com/fnielsen/scholia/issues/1084#issue-586691879 , which represent two different use cases behind the two changes in the patch (removing the LIMIT, adding 1 as another step).

**Comment by Daniel-Mietchen** [comment]
Not sure about the explanation of the dot colour either, but I just added #1087 for that.

**Comment by egonw** [comment]
> Not sure what you mean by the fewer dots. If that refers to the two pics in [#1085 (comment)](https://github.com/fnielsen/scholia/pull/1085#issuecomment-603021008) , then they do not have to be compared against each other

Oh, sorry, I thought they were before after :)

**Comment by egonw** [comment]
> Not sure about the explanation of the dot colour either, but I just added #1087 for that.

Ah. awesome. @Daniel-Mietchen, you can actually push additional patches to existing pull requests. I will see if I can merge in #1087 into this branch.

**Comment by Daniel-Mietchen** [comment]
I purposefully kept the explanation commit separate, since I am not sure that's what we need. But I take your merge as a yes and am merging all of it into master now.

**Pull request merged**
