### PR TITLE
Also handle subprojects (via participant)

### PR DESCRIPTION
**Pull request by egonw**
Bascially implementing `(wdt:P1344|^wdt:P710)` in the various sections.

### CODE REVIEW

**Comment by fnielsen** [comment]
eNanoMapper no longer shows the participants on the map: http://127.0.0.1:8100/project/Q27990087

**Comment by fnielsen** [comment]
I think the branch is slightly behind the master: https://github.com/fnielsen/scholia/network

**Comment by egonw** [comment]
@fnielsen, ok, I rebased the patch and added a fix for eNanoMapper...

**Comment by egonw** [comment]
OK, now really OK?

**Comment by egonw** [comment]
@fnielsen, please let me know if you think there are further things I should do...

**Comment by Daniel-Mietchen** [comment]
Looks good to me - planning to feature this in a talk tomorrow if it's live by then.

**Pull request merged**
