### PR TITLE
Clean rebase of the latest WikiPathways patch

### PR DESCRIPTION
**Pull request by egonw**
Derived from https://github.com/fnielsen/scholia/pull/877

### CODE REVIEW

**Comment by egonw** [comment]
Okay, it works for me. I like the listing of both authors on the external source and the table for authors whom are also on Wikidata.

@AlexanderPico, did you check what happens for a WikiPathways which actually has a page in Wikipedia (there are a few)? Do we get duplication descriptions there?

**Comment by egonw** [comment]
@fnielsen, I think the patch is good to go. Duplicate descriptions should be pretty rare, and I think we can solve that later.

**Comment by AlexanderPico** [comment]
There are no duplications that I'm aware of. We have been adding interactive pathway templates to select Wikipedia articles for years, but these are not articles *about* the WikiPathways item. Please share a link if you're talking about something else that I've missed. Thanks!

**Comment by AlexanderPico** [comment]
And thanks for the review! We tried a few different strategies for authors, trying to follow prior examples from other Scholia templates. We were pleased with this final combo of a listing and a table as well. I think it will serve many use cases effectively and encourage proper Wikidata (and ORCID) identification of authors going forward.

**Comment by AlexanderPico** [comment]
Anything else I can do to clarify or fix this patch?

**Comment by fnielsen** [comment]
1. There are lots of white space errors
2. Uncommented debug code.
3. Inconsistent service labeling.
4. Not clear to me whether the creation of lists with Javascript is good. For instance, authors list seem to be there twice. I think we should make a more principaled approach of displaying the information.
5. Unclear if the is unescape variable being interpolated.
6. Naming between Javascript and HTML ids is an issues, e.g., authorTable.

I have a dangling branch here: https://github.com/fnielsen/scholia/commit/eaeff4303e894fbd5e1b40f00c780972e0ac1675 This does not clear all.

**Comment by AlexanderPico** [comment]
Thanks for the thorough feedback @fnielsen! I re-read the CONTRIBUTING doc and realized that I missed the important bit about `tox` for testing and style checking. I will run that in the future.

Thanks for the initial clean up. I have responses for your other questions as well, but I think it might be easier to do this in smaller chunks.

I will take the clean up work you've already done and submit PRs for isolated additions with more careful formatting and explanations.

Sorry for the hassle!

**Comment by AlexanderPico** [comment]
Please see https://github.com/fnielsen/scholia/pull/909 for a cleaned up version of the current pathway template from `master` for a clean background for new features.

**Comment by fnielsen** [comment]
I apply #909 to master. What does that mean wrt. to this pull request?

**Comment by AlexanderPico** [comment]
Thanks @fnielsen. This PR can be closed. I am refactoring it into a series of smaller, more isolated PRs for clarity. My goal is to issue PRs that are quick and easy for you all to review and merge :)

**Pull request closed without merging**
