### PR TITLE
Migrated another query to the new code design

### PR DESCRIPTION
**Pull request by egonw**
Had a spare few minutes...

### CODE REVIEW

**Comment by fnielsen** [comment]
A bad new is that the resolving of properties are not yet implemented :(

**Comment by egonw** [comment]
Oh, right... is that blocking this patch? (if so, fine... just determining a next step...)

**Comment by fnielsen** [comment]
I am extending it now

**Comment by fnielsen** [comment]
Now in production https://tools.wmflabs.org/scholia/work/Q27932040 https://tools.wmflabs.org/scholia/P680

**Comment by egonw** [comment]
Looks great!

**Comment by fnielsen** [comment]
This related to #49

**Pull request merged**
