### PR TITLE
Add conference poster (wd:Q54670950) to co-author graph query in Organization aspect

### PR DESCRIPTION
**Pull request by cthoyt**
It's pretty hard to see the diff, but I just added "%20wd%Q54670950" after the previous item "%20wd%3AQ947859"

### CODE REVIEW

**Comment by fnielsen** [comment]
Do we have a test example organization? I am wondering whether https://tools.wmflabs.org/scholia/organization/Q1451981 would do?

**Comment by cthoyt** [comment]
Yes - if the query is working correctly (I actually tested this query on Fraunhofer, since it is my workplace) we should see an edge appear between my name and Marc Zimmerman (I did indeed see this).

I could try writing a unit test for this as well. Was there a reason why some queries were written as javascript and some were made with iframes? I would prefer the javascript because they could also be handled as templates

**Comment by fnielsen** [comment]
> Was there a reason why some queries were written as javascript and some were made with iframes? I would prefer the javascript because they could also be handled as templates

Yes. We have not yet programmed the plots with Javascript (except for the work-topic matrix), so we rely entirely on WDQS' plots, - which is suboptimal. This has been up for some time, see #69. The matrix visualization from May 2019 is the only one non-WDQS visualization we implemented so far, - and event that could be improved #721.

**Comment by fnielsen** [comment]
I get "jQuery.Deferred exception: malformed URI sequence"

**Comment by fnielsen** [comment]
it think "%Q54670950" is the problem. You need an escaped colon.

**Comment by fnielsen** [comment]
The patch name could be more telling.

**Comment by cthoyt** [comment]
Sorry about the patch name - I made it from the GitHub web interface and it's not so obvious how to change. Thanks for the fix!

**Comment by fnielsen** [comment]
This should be working now, e.g., https://tools.wmflabs.org/scholia/organization/Q1451981

**Pull request merged**
