### PR TITLE
add country-level citation graph per topic

### PR DESCRIPTION
**Pull request by Daniel-Mietchen**
First attempt at #1101.

Worked for all the about two dozen topics I tested, except for https://tools.wmflabs.org/scholia/topic/Q3450985 (neurodevelopmental disorders), which gave an empty response.

### CODE REVIEW

**Comment by Daniel-Mietchen** [comment]
Another quirk: for microstructure, the flag for South Africa was just shown as the flag from the Apartheid period. This was easily [fixed](https://www.wikidata.org/w/index.php?title=Q160250&diff=prev&oldid=1151580302) but should be kept in mind.

Also, while tracking this down, I was reminded that we have [flag image (P41)](https://www.wikidata.org/wiki/Property:P41), which will likely make the query faster.

Screenshot_2020-04-06 Scholia

**Comment by Daniel-Mietchen** [comment]
The solution to the question as to why https://tools.wmflabs.org/scholia/topic/Q3450985 (neurodevelopmental disorders) did not yield any result was simply that there were too few topic annotations (15 right now).

Screenshot_2020-04-06 Wikidata Query Service

I am starting a [first batch](https://tools.wmflabs.org/quickstatements/#/batch/28518) towards changing that.

**Comment by egonw** [comment]
I checked the `tox` report and there are no problems.

**Comment by fnielsen** [comment]
I am unfamiliar with the `target:` notation.

**Comment by Daniel-Mietchen** [comment]
@fnielsen See #431 for the ```target:``` notation.

**Pull request merged**
