### PR TITLE
Show the ORCID for authors (if available)

### PR DESCRIPTION
**Pull request by egonw**
Which makes it look like:

image

@fnielsen, if you are OK, I can add an icon later...

### CODE REVIEW

**Comment by egonw** [comment]
Image patch pending....

**Comment by egonw** [comment]
New layout:

image

**Comment by fnielsen** [comment]
There is still an issue around the logo. I disabled it because of Toolforge rules/privacy.

**Comment by egonw** [comment]
Oh, it's the icon being on a different server?

**Comment by fnielsen** [comment]
Yes.

**Comment by fnielsen** [comment]
Is there a copyright on the icon?

**Comment by egonw** [comment]
Don't think so: https://orcid.org/trademark-and-id-display-guidelines

**Comment by alainna** [comment]
CC-0 :) Let us know if you'd like it in another format!

**Comment by egonw** [comment]
@alainna, I left a comment on Figshare... the icons there are square, but the Display Guidelines has round icons, which I actually like more... are those also available from Figshare?

**Comment by alainna** [comment]
@egonw hum! The iD icons should download as a square, with the background displaying as transparent. Let me know if that's not the case and I'll a) provide direct links here, and b) update the Figshare listing 😄

**Pull request merged**
