### PR TITLE
Added Mastodon support to the author aspect

### PR DESCRIPTION
**Pull request by egonw**
image

Logo from Wikimedia Commons.

### CODE REVIEW

**Comment by fnielsen** [comment]
You example with Egon writes "The page you are looking for isn't here. "

**Comment by egonw** [comment]
@fnielsen, sorry about that. I'm 100% sure I tested it (successfully). Fixed now.

**Comment by fnielsen** [comment]
This PR seems lost. I have tried to cherry-pick a commit but cannot find an appropriate

**Comment by fnielsen** [comment]
What issue does this refer to?

**Comment by egonw** [comment]
Indeed. Weird, because the original merge did merge them correctly. I took the liberty of cherry-picking them directly into `master`.

**Pull request merged**
