### PR TITLE
Feature to view taxons

### PR DESCRIPTION
**Pull request by egonw**
image

### CODE REVIEW

**Comment by fnielsen** [comment]
https://tools.wmflabs.org/scholia/taxon/Q15978631

**Comment by fnielsen** [comment]
I am wondering whether we can use the space in the table columns to display something useful, e.g., an example publication with P921?

**Comment by pigsonthewing** [comment]
Thank you. 

Unfortunately, this seems buggy. The parent taxa on https://tools.wmflabs.org/scholia/taxon/Q25485 do not match the one on https://www.wikidata.org/wiki/Q168473#P171

For example, Scholia has:

- Squamata | order
- Saurischia | order
- Passeriformes | order

while Wikidata only has the last of these.

**Comment by fnielsen** [comment]
Well spotted! This is strange. I cannot see where the error is. Perhaps a Wikidata item further up in the hierarchy is linking it wrongly...

**Comment by fnielsen** [comment]
http://tinyurl.com/y82crtk5  The bird class leads to a Coelurosauria suborder. That is wrong. It is through Paraves, Pennaraptora, Maniraptora, Maniraptoriformes. This will need to be fixed in Wikidata.

```
#defaultView:Graph
SELECT
  ?child ?childLabel
  ?parent ?parentLabel
WHERE {
  SELECT ?child ?childLabel ?parent ?parentLabel WHERE {
    service gas:service {
      gas:program gas:gasClass "com.bigdata.rdf.graph.analytics.BFS" ;
                  gas:in wd:Q168473 ; 
                  gas:traversalDirection "Forward" ;
                  gas:out ?child ;
                  gas:out1 ?depth ;
                  gas:out2 ?parent1 ;
                  gas:linkType wdt:P171 ;
                  gas:maxIterations 20;
                  gas:maxVisited 200 .
    }
    ?child wdt:P171 ?parent .
    ?child rdfs:label ?child_label . FILTER(LANG(?child_label) = 'en')
    ?parent rdfs:label ?parent_label . FILTER(LANG(?parent_label) = 'en')
    OPTIONAL {
      ?child wdt:P105 ?rank .
      ?rank rdfs:label ?rank_label_ . FILTER (LANG(?rank_label_) = 'en')
    }
    BIND(CONCAT(?child_label, " - ", COALESCE(?rank_label_, "???")) AS ?childLabel)
    BIND(CONCAT(?parent_label, " - ") AS ?parentLabel)
  }
}
```

**Comment by fnielsen** [comment]
The above graph query is now part of the taxon aspect.

**Pull request merged**
