### PR TITLE
changing the text for the leftmost menu button from "Scholia" to "Home"

### PR DESCRIPTION
**Pull request by Daniel-Mietchen**
to improve user navigation, as per https://en.wikipedia.org/w/index.php?title=Template_talk:Scholia&oldid=922620697 .

### CODE REVIEW

**Comment by fnielsen** [comment]
One is that with this change we do not have any indication of that this is Scholia.

**Comment by egonw** [comment]
We can also replace the text with the logo?

**Comment by Daniel-Mietchen** [comment]
Yes, replacing this with the logo would make sense.

**Comment by Daniel-Mietchen** [comment]
This is now superseded by #956 .

**Pull request closed without merging**
