### PR TITLE
Report the taxons a compound is found in (with source)

### PR DESCRIPTION
**Pull request by egonw**
New in the `chemical` aspect:

image

### CODE REVIEW

**Comment by fnielsen** [comment]
What is the example?

**Comment by fnielsen** [comment]
> What is the example?

I found an example. There are apparently benzen in species!

**Comment by fnielsen** [comment]
Maybe there should be an indication of the DOI going outside Scholia

**Comment by egonw** [comment]
> Maybe there should be an indication of the DOI going outside Scholia

Did you create a ticket for that? We have a lot of links out across the aspects.

**Comment by fnielsen** [comment]
> Did you create a ticket for that? We have a lot of links out across the aspects.

No

**Pull request merged**
