### PR TITLE
New aspect for chemical elements

### PR DESCRIPTION
**Pull request by egonw**
Some screenshots:

image

image

(Interestingly, in the latter screenshot 12C is missing :)

### CODE REVIEW

**Comment by fnielsen** [comment]
I see a merging conflict.

**Comment by egonw** [comment]
Okay, not good. I will rebase.

**Comment by fnielsen** [comment]
Could it be due to my out-of-order PR handling?

**Comment by egonw** [comment]
Replaced by this PR: https://github.com/fnielsen/scholia/pull/821

**Pull request closed without merging**
