### PR TITLE
Add events attended/participated/organized to author aspect

### LINKED ISSUE #849: Add conferences participated to author page
I've borrowed some of the SPARQL query from the event page that makes a list of attendees for a conference and flipped it to list all of the conferences attended by an individual. Below is the SPARQL (the BIND just after the WHERE points to my wikidata page - this part would need to be formatted in based on the page the user is viewing). Try it at the Wikidata Query Service at https://w.wiki/9gT.

```sparql
SELECT
  ?role
  ?conference ?conferenceLabel
  ?locationLabel
  ?hashtag
WHERE {
    BIND(wd:Q47475003 as ?person)
    {  # speaker
      ?conference wdt:P823 ?person .
      BIND("speaker" AS ?role)
    }
    UNION
    {  # organizer
      ?conference wdt:P664 ?person .
      BIND("organizer" AS ?role)
    }
    UNION
    {  # participant
      ?person wdt:P1344 | ^wdt:P710 ?conference  .
      BIND("participant" AS ?role)
    }
    UNION
    {  # editor
      ?person ^wdt:P98 / wdt:P4745 ?conference  .
      BIND("editor of proceedings" AS ?role)
    }
    UNION
    {  # author
      ?person ^wdt:P50 / wdt:P1433 / wdt:P4745 ?conference  .
      BIND("author" AS ?role)
    }
    UNION
    {  # program committee member
      ?conference wdt:P5804 ?person .
      BIND("program committee member" AS ?role)
    }
    OPTIONAL { ?conference wdt:P276 ?location }
    OPTIONAL { ?conference wdt:P2572 ?hashtag }
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,no,ru,sv,zh". }  
}
```

Edit: might need a bit of work w.r.t. grouping the data in case an individual had several roles at a given conference, if the conference had multiple locations, or multiple hashtags.

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #849

I've made a SPARQL query that queries the conference, its year, the authors' roles, and the locations. It now is displayed as a table in the author aspect. It gets added to a table using `sparqlToDataTable`.

There are some comments for extensions to the SPARQL query the conference's short names and hashtag, in case you think that might also be interesting.

Two differences from the other parts of this aspect:

- I used `BIND` in SPARQL rather than using `{{ q }}` several times
- The table has the `table-striped` class. If you disagree with this, then I can remove it :)

I tested locally with http://localhost:8100/author/Q20895241 and got:

Screenshot 2019-10-15 22 27 41

### CODE REVIEW

**Comment by Daniel-Mietchen** [comment]
What about linking the locations to their Scholia page in the location aspect?

**Comment by cthoyt** [comment]
I like that idea but I don’t think the JavaScript function can automatically add links in a group concatenation. Do you know a way to do this? Because then I would also suggest adding links to other tables that have this kind of concatenation like the author list in each publication in the list of publications at the top of the author aspect

**Comment by fnielsen** [comment]
1. "Conferences Attended" -> Lowercase second word
2. Perhaps headline and the "conference" column should be called "event"?
3. What we should do with the service labeling is still up for discussion, but I think that we should put the "[AUTO_LANGUAGE]" in front.
4. "year" and "as" should be capital.
5. The second column should go to the "event" aspect rather than the root.

**Comment by fnielsen** [comment]
Sorry, I already addded the changes.

**Comment by cthoyt** [comment]
@fnielsen thanks for the feedback! Is there anything to be done here? It looks like you merged the code to master but the PR is still open

**Comment by fnielsen** [comment]
Now running, e..g, https://tools.wmflabs.org/scholia/author/Q20980928

**Comment by fnielsen** [comment]
@cthoyt Sorry, for my mess up. Had I known you were that fast responding, I would not have started editing. Let me know if there is something I missed in my edits.

**Pull request closed without merging**
