### PR TITLE
Split out the statistics page

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by egonw** [comment]
NOT READY YET

**Comment by fnielsen** [comment]
Thanks for the PR. I would rather like to have the name "statistics" to avoid abbreviations, like we usually do for the pages.

**Comment by egonw** [comment]
> Thanks for the PR. I would rather like to have the name "statistics" to avoid abbreviations, like we usually do for the pages.

@fnielsen, done.

**Comment by fnielsen** [comment]
This branch seems ot have been started from an old master.

**Comment by fnielsen** [comment]
> This branch seems ot have been started from an old master.

It probably does not matter.

**Pull request merged**
