### PR TITLE
Give all sections on all Scholia pages section IDs (Issue fix #1157)

### LINKED ISSUE #1157: Give all sections on all Scholia pages suitable section IDs
e.g. in author profiles like https://tools.wmflabs.org/scholia/author/Q4693015 , sections like the most recent publications do not currently have such an ID.

### PR DESCRIPTION
**Pull request by ammar257ammar**
Dear all,

Please check this pull request as it resolves issue #1157 

All (26 templates with 60-70 HTML files) sections headings, tables and iframes were provided with proper IDs that complies with W3's CSS naming conventions:
[https://www.w3.org/TR/CSS2/syndata.html#characters](https://www.w3.org/TR/CSS2/syndata.html#characters)

Thank you.

Sincerely,
Ammar

### CODE REVIEW

**Comment by fnielsen** [comment]
The id for wembedder is used in the scholia/app/templates/base.html javascript code. That should just be "wembedder" across all pages.

**Comment by egonw** [comment]
Looks good to me. It add missing `@id` attributes and gives them all the same structure. I do not know all the discussion around this patch, so might be missing relevant criteria.

**Comment by ammar257ammar** [comment]
I fixed the wembedder ids in all pages, please check.

**Comment by egonw** [comment]
@ammar257ammar, can you plz run that `tox` command and check if it doesn't give errors?

**Comment by fnielsen** [comment]
There seems to be numerous failures?
* http://127.0.0.1:8100/event-series/Q17012957
* For instance, "list-of-publications" cannot be renamed to "list-of-publications-table" because the Javascript uses the name.
* Another example: http://127.0.0.1:8100/chemical/Q18216

**Pull request merged**
