### PR TITLE
Convert location aspects to external SPARQL #1281

### PR DESCRIPTION
**Pull request by fnielsen**
Here is converted location and location-topic, but not country.
One panel in location "Nearby locations as topics in works" seems to
time out and should be improved.
On the location-topic aspect the SPARQL query has been improved
for query time performance with and wikibase:around SERVICE query.

### CODE REVIEW

**Comment by egonw** [comment]
@fnielsen, not worth changing, but it would be easier for me as reviewer if a SPARQL optimization would be in a separate patch (still in the same PR would be fine), which makes it a lot easier to see what changed.

**Comment by egonw** [comment]
"Nearby locations as topics in works" problem confirmed. Did you file a but report for that? I get no error messages, no data. In the console I did see a 500 at some point.

**Review by egonw — APPROVED** [review]
Left two comments, but generally looks good. `tox` is happy.

**Comment by Daniel-Mietchen** [comment]
In the location-topic subaspect, the topic is still not indicated. I could not find a ticket for that, so I just opened a new one at https://github.com/fnielsen/scholia/issues/1292 .

**Comment by Daniel-Mietchen** [comment]
> "Nearby locations as topics in works" problem confirmed. Did you file a but report for that? I get no error messages, no data. In the console I did see a 500 at some point.

There is https://github.com/fnielsen/scholia/issues/517 for that.

**Comment by Daniel-Mietchen** [comment]
> On the location-topic aspect the SPARQL query has been improved
> for query time performance with and wikibase:around SERVICE query.

There is https://github.com/fnielsen/scholia/issues/1015 for that query.

**Comment by Daniel-Mietchen** [comment]
We also have https://github.com/fnielsen/scholia/issues/335 for "Nearby organizations in location-topic subaspect".

**Review by Daniel-Mietchen — APPROVED** [review]
I think the externalization part looks fine, and the points that need improvement all have their dedicated tickets, so I'm fine with this being merged.

**Pull request merged**
