### PR TITLE
Added a 2D depiction of the chemical using the public CDKDepict servi…

### PR DESCRIPTION
**Pull request by egonw**
…ce and the SMILES from Wikidata (implements #353)

Pretty pleased with the result :)

image

### CODE REVIEW

**Comment by fnielsen** [comment]
scholia-chemical-3d-alignment
There is a bit of an issue with the alignment

**Comment by fnielsen** [comment]
Running https://tools.wmflabs.org/scholia/chemical/Q2270

**Comment by fnielsen** [comment]
I have reverted the merge I did of your pull request, because of the use of thirdparty webservice.

"Embedding external resources (fonts, css, javascript, images, etc) from any third-party into webpages hosted on Toolforge or other Cloud VPS projects causes a potential conflict with the Wikimedia Privacy Policy." - https://phabricator.wikimedia.org/phame/post/view/65/toolforge_provides_proxied_mirrors_of_cdnjs_and_now_fontcdn_for_your_usage_and_user-privacy/

**Comment by egonw** [comment]
Oh... :(

**Pull request merged**
