### PR TITLE
Work aspect "/export" page giving BiBTeX and CITATION.cff. Input wanted.

### PR DESCRIPTION
**Pull request by egonw**
Using citation-js. Result:

image

Reviewers, what do you think of such a feature?

### CODE REVIEW

**Comment by fnielsen** [comment]
I think the feature is good. I am not sure about the URL though.

**Comment by egonw** [comment]
> I think the feature is good. I am not sure about the URL though.

Got a suggestion?

**Comment by egonw** [comment]
`CITATION.cff` screenshot: 

image

**Comment by egonw** [comment]
Updating the citation-js version:

image

**Comment by Daniel-Mietchen** [comment]
Maybe use "bibformats" instead of "export"?

**Comment by egonw** [comment]
@fnielsen, what do you think of Daniel's suggestion? I am impartial.

**Comment by egonw** [comment]
Rebased on the master of now

**Comment by egonw** [comment]
@fnielsen, can you please let me know what the next step is here?

**Pull request merged**
